### ISSUE TITLE
Deprecated NineOlds

### ISSUE THREAD

**Issue by ppamorim** [eure/citrus#1]
Use ViewCompat from appCompat instead NineOlds. This is deprecated.

**Comment by gotokatsuya** [comment]
Hi @ppamorim 

Yes, that's right. I used it because it is very easy to write some animations.
But, I think it is not better to use a deprecated library. I will try to use ViewCompat.

Work-in-progress : [develop branch](https://github.com/eure/citrus/tree/develop)

Thanks.

**Comment by shkschneider** [comment]
+1

**Comment by gotokatsuya** [comment]
Merged develop !
