### ISSUE TITLE
Bugs when using Android Support 22.2.1

### ISSUE THREAD

**Issue by joielechong** [eure/citrus#3]
First, Thank you for your app, beautiful app than I use as my base project.

There is a bug when I change android support from version 22.2.0 to 22.2.1, scrolling recyclerview  up don't hide action bar menu like before. So now I'll stick with version 22.2.0.

**Comment by gotokatsuya** [comment]
Hi @joielechong .

You're welcome. Thank you for using.

Oh, Really? We will update `22.2.1` and check if our project is operational soon.

If we can fix a bug, citrus will be updated！

Thank you for contacting us.

**Comment by joielechong** [comment]
Thank you for your hardworking.
The bug is happening if I use compile 'com.android.support:design:22.2.1' instead of compile 'com.android.support:design:22.2.0'.

btw, maybe you can add layout rotation handle to Citrus too.

**Comment by gotokatsuya** [comment]
@joielechong 

OK. Thank you.

Yes, I can but it's too hard :-P
I'm waiting for your pull-request.

**Comment by joielechong** [comment]
Well, I also a beginner with git too.
I really like to help you, maybe you could teach me one and two about git and pr :P..

**Comment by gotokatsuya** [comment]
Haha, it's too hard too :sunglasses:

**Comment by joielechong** [comment]
I guest I must go on with the wind..:P.

I'll try to learn it and maybe trying to make a pr in a couple days.

**Comment by gotokatsuya** [comment]
Great ! :smile:
